# Generated by Django 5.1.1 on 2026-04-11 23:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecocardiograma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conclusiónecocardiograma',
            name='comentario_concordancia',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(512)]),
        ),
        migrations.AlterField(
            model_name='conclusiónecocardiograma',
            name='comentario_defectos',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(512)]),
        ),
        migrations.AlterField(
            model_name='conclusiónecocardiograma',
            name='comentario_final',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(8000)]),
        ),
        migrations.AlterField(
            model_name='conclusiónecocardiograma',
            name='comentario_motilidad',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(512)]),
        ),
        migrations.AlterField(
            model_name='conclusiónecocardiograma',
            name='comentario_pericardio',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(512)]),
        ),
        migrations.AlterField(
            model_name='conclusiónecocardiograma',
            name='comentario_situs',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(512)]),
        ),
        migrations.AlterField(
            model_name='conclusiónecocardiograma',
            name='comentario_valvula_aortica',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(512)]),
        ),
        migrations.AlterField(
            model_name='conclusiónecocardiograma',
            name='comentario_valvula_mitral',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(512)]),
        ),
        migrations.AlterField(
            model_name='conclusiónecocardiograma',
            name='comentario_valvula_pulmonar',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(512)]),
        ),
        migrations.AlterField(
            model_name='conclusiónecocardiograma',
            name='comentario_valvula_tricuspide',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(512)]),
        ),
        migrations.AlterField(
            model_name='conclusiónecocardiograma',
            name='comentario_vasos',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(512)]),
        ),
        migrations.AlterField(
            model_name='conclusiónecocardiograma',
            name='conclusion_texto',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(8000)]),
        ),
    ]
