# Generated by Django 5.1.1 on 2026-02-10 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0003_rename_idpaciente_idx_historia_paciente_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcostressEstudio',
            fields=[
                ('id_stress', models.AutoField(db_column='idStress', primary_key=True, serialize=False)),
                ('indicacion_estudio', models.TextField(blank=True, db_column='indicacionEstudio', null=True)),
                ('tipo_apremio', models.TextField(blank=True, db_column='tipoApremio', null=True)),
                ('medicacion_momento_estudio', models.TextField(blank=True, db_column='medicacionMomentoEstudio', null=True)),
                ('medico_solicitante', models.TextField(blank=True, db_column='medicoSolicitante', null=True)),
                ('frecuencia_cardiaca_basal', models.TextField(blank=True, db_column='frecuenciaCardiacaBasal', null=True)),
                ('frecuencia_cardiaca_maxima', models.TextField(blank=True, db_column='frecuenciaCardiacaMaxima', null=True)),
                ('presion_arterial_basal_inicial', models.TextField(blank=True, db_column='presionArterialBasalInicial', null=True)),
                ('presion_arterial_basal_final', models.TextField(blank=True, db_column='presionArterialBasalFinal', null=True)),
                ('presion_arterial_maxima_inicial', models.TextField(blank=True, db_column='presionArterialMaximaInicial', null=True)),
                ('presion_arterial_maxima_final', models.TextField(blank=True, db_column='presionArterialMaximaFinal', null=True)),
                ('informe_ergometria', models.TextField(blank=True, db_column='informeErgometria', null=True)),
                ('datos_ecocardiograficos_basales', models.TextField(blank=True, db_column='datosEcocardiograficosBasales', null=True)),
                ('datos_ecocardiograficos_post_esfuerzo_inmediato', models.TextField(blank=True, db_column='datosEcocardiograficosPostEsfuerzoInmediato', null=True)),
                ('conclusion', models.TextField(blank=True, db_column='conclusion', null=True)),
                ('historia', models.ForeignKey(db_column='idHC', on_delete=django.db.models.deletion.CASCADE, related_name='ecostress_estudios', to='main.historiaclinica')),
            ],
            options={
                'verbose_name': 'Estudio de ecostress',
                'verbose_name_plural': 'Estudios de ecostress',
                'db_table': 'stress',
                'indexes': [models.Index(fields=['historia'], name='stress_historia_idx')],
            },
        ),
    ]
