# Generated by Django 5.1.1 on 2026-02-10 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecostress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecostressestudio',
            name='fecha_estudio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
