# Generated by Django 5.1.1 on 2026-04-11 23:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecostress', '0002_ecostressestudio_fecha_estudio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecostressestudio',
            name='conclusion',
            field=models.TextField(blank=True, db_column='conclusion', null=True, validators=[django.core.validators.MaxLengthValidator(8000)]),
        ),
        migrations.AlterField(
            model_name='ecostressestudio',
            name='datos_ecocardiograficos_basales',
            field=models.TextField(blank=True, db_column='datosEcocardiograficosBasales', null=True, validators=[django.core.validators.MaxLengthValidator(512)]),
        ),
        migrations.AlterField(
            model_name='ecostressestudio',
            name='datos_ecocardiograficos_post_esfuerzo_inmediato',
            field=models.TextField(blank=True, db_column='datosEcocardiograficosPostEsfuerzoInmediato', null=True, validators=[django.core.validators.MaxLengthValidator(512)]),
        ),
        migrations.AlterField(
            model_name='ecostressestudio',
            name='frecuencia_cardiaca_basal',
            field=models.TextField(blank=True, db_column='frecuenciaCardiacaBasal', null=True, validators=[django.core.validators.MaxLengthValidator(512)]),
        ),
        migrations.AlterField(
            model_name='ecostressestudio',
            name='frecuencia_cardiaca_maxima',
            field=models.TextField(blank=True, db_column='frecuenciaCardiacaMaxima', null=True, validators=[django.core.validators.MaxLengthValidator(512)]),
        ),
        migrations.AlterField(
            model_name='ecostressestudio',
            name='indicacion_estudio',
            field=models.TextField(blank=True, db_column='indicacionEstudio', null=True, validators=[django.core.validators.MaxLengthValidator(512)]),
        ),
        migrations.AlterField(
            model_name='ecostressestudio',
            name='informe_ergometria',
            field=models.TextField(blank=True, db_column='informeErgometria', null=True, validators=[django.core.validators.MaxLengthValidator(512)]),
        ),
        migrations.AlterField(
            model_name='ecostressestudio',
            name='medicacion_momento_estudio',
            field=models.TextField(blank=True, db_column='medicacionMomentoEstudio', null=True, validators=[django.core.validators.MaxLengthValidator(512)]),
        ),
        migrations.AlterField(
            model_name='ecostressestudio',
            name='medico_solicitante',
            field=models.TextField(blank=True, db_column='medicoSolicitante', null=True, validators=[django.core.validators.MaxLengthValidator(512)]),
        ),
        migrations.AlterField(
            model_name='ecostressestudio',
            name='presion_arterial_basal_final',
            field=models.TextField(blank=True, db_column='presionArterialBasalFinal', null=True, validators=[django.core.validators.MaxLengthValidator(512)]),
        ),
        migrations.AlterField(
            model_name='ecostressestudio',
            name='presion_arterial_basal_inicial',
            field=models.TextField(blank=True, db_column='presionArterialBasalInicial', null=True, validators=[django.core.validators.MaxLengthValidator(512)]),
        ),
        migrations.AlterField(
            model_name='ecostressestudio',
            name='presion_arterial_maxima_final',
            field=models.TextField(blank=True, db_column='presionArterialMaximaFinal', null=True, validators=[django.core.validators.MaxLengthValidator(512)]),
        ),
        migrations.AlterField(
            model_name='ecostressestudio',
            name='presion_arterial_maxima_inicial',
            field=models.TextField(blank=True, db_column='presionArterialMaximaInicial', null=True, validators=[django.core.validators.MaxLengthValidator(512)]),
        ),
        migrations.AlterField(
            model_name='ecostressestudio',
            name='tipo_apremio',
            field=models.TextField(blank=True, db_column='tipoApremio', null=True, validators=[django.core.validators.MaxLengthValidator(512)]),
        ),
    ]
