# Generated by Django 5.1.1 on 2026-02-20 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("main", "0003_rename_idpaciente_idx_historia_paciente_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DopplerEstudio",
            fields=[
                (
                    "id_doppler",
                    models.AutoField(db_column="idDoppler", primary_key=True, serialize=False),
                ),
                (
                    "art_fem_comun_derecha",
                    models.TextField(blank=True, db_column="artFemComunDerecha", null=True),
                ),
                (
                    "art_fem_superficial_derecha",
                    models.TextField(
                        blank=True, db_column="artFemSuperficialDerecha", null=True
                    ),
                ),
                (
                    "art_fem_profunda_derecha",
                    models.TextField(blank=True, db_column="artFemProfundaDerecha", null=True),
                ),
                (
                    "art_poplitea_derecha",
                    models.TextField(blank=True, db_column="artPopliteaDerecha", null=True),
                ),
                (
                    "art_infrapatelares_derecha",
                    models.TextField(
                        blank=True, db_column="artInfrapatelaresDerecha", null=True
                    ),
                ),
                (
                    "art_fem_comun_izquierda",
                    models.TextField(blank=True, db_column="artFemComunIzquierda", null=True),
                ),
                (
                    "art_fem_superficial_izquierda",
                    models.TextField(
                        blank=True, db_column="artFemSuperficialIzquierda", null=True
                    ),
                ),
                (
                    "art_fem_profunda_izquierda",
                    models.TextField(blank=True, db_column="artFemProfundaIzquierda", null=True),
                ),
                (
                    "art_poplitea_izquierda",
                    models.TextField(blank=True, db_column="artPopliteaIzquierda", null=True),
                ),
                (
                    "art_infrapatelares_izquierda",
                    models.TextField(
                        blank=True, db_column="artInfrapatelaresIzquierda", null=True
                    ),
                ),
                (
                    "conclusion",
                    models.TextField(blank=True, db_column="conclusion", null=True),
                ),
                (
                    "historia",
                    models.ForeignKey(
                        db_column="idHC",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doppler_estudios",
                        to="main.historiaclinica",
                    ),
                ),
            ],
            options={
                "verbose_name": "Doppler arterial de miembros inferiores",
                "verbose_name_plural": "Doppler arterial de miembros inferiores",
                "db_table": "doppler",
                "indexes": [
                    models.Index(fields=["historia"], name="doppler_historia_idx")
                ],
            },
        ),
    ]
