# Generated by Django 5.1.1 on 2026-02-05 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_inx_fix_sexo'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='historiaclinica',
            new_name='historia_paciente_idx',
            old_name='idPaciente_idx',
        ),
        migrations.RenameIndex(
            model_name='indicacionesvisitas',
            new_name='indicaciones_fecha_idx',
            old_name='ind_fecha_idx',
        ),
        migrations.RenameIndex(
            model_name='indicacionesvisitas',
            new_name='ind_hist_fecha_idx',
            old_name='ind_his_fecha_idx',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='idTipoDoc',
            field=models.ForeignKey(db_column='idTipoDoc_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='main.tipodocumento'),
        ),
        migrations.AddIndex(
            model_name='indicacionesvisitas',
            index=models.Index(fields=['historia_clinica'], name='indicaciones_historia_idx'),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['idTipoDoc'], name='pacientes_tipo_doc_idx'),
        ),
        migrations.AddIndex(
            model_name='signosvitales',
            index=models.Index(fields=['historia'], name='signos_vitales_historia_idx'),
        ),
        migrations.AddIndex(
            model_name='signosvitales',
            index=models.Index(fields=['fecha'], name='signos_vitales_fecha_idx'),
        ),
    ]
