# Generated by Django 5.1.1 on 2026-02-27 13:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmii', '0002_migrate_from_doppler'),
    ]

    operations = [
        migrations.AddField(
            model_name='mmiiestudio',
            name='fecha_estudio',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
