# Generated by Django 5.1.1 on 2026-04-11 23:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmii', '0003_mmiiestudio_fecha_estudio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mmiiestudio',
            name='art_fem_comun_derecha',
            field=models.TextField(blank=True, db_column='artFemComunDerecha', null=True, validators=[django.core.validators.MaxLengthValidator(512)]),
        ),
        migrations.AlterField(
            model_name='mmiiestudio',
            name='art_fem_comun_izquierda',
            field=models.TextField(blank=True, db_column='artFemComunIzquierda', null=True, validators=[django.core.validators.MaxLengthValidator(512)]),
        ),
        migrations.AlterField(
            model_name='mmiiestudio',
            name='art_fem_profunda_derecha',
            field=models.TextField(blank=True, db_column='artFemProfundaDerecha', null=True, validators=[django.core.validators.MaxLengthValidator(512)]),
        ),
        migrations.AlterField(
            model_name='mmiiestudio',
            name='art_fem_profunda_izquierda',
            field=models.TextField(blank=True, db_column='artFemProfundaIzquierda', null=True, validators=[django.core.validators.MaxLengthValidator(512)]),
        ),
        migrations.AlterField(
            model_name='mmiiestudio',
            name='art_fem_superficial_derecha',
            field=models.TextField(blank=True, db_column='artFemSuperficialDerecha', null=True, validators=[django.core.validators.MaxLengthValidator(512)]),
        ),
        migrations.AlterField(
            model_name='mmiiestudio',
            name='art_fem_superficial_izquierda',
            field=models.TextField(blank=True, db_column='artFemSuperficialIzquierda', null=True, validators=[django.core.validators.MaxLengthValidator(512)]),
        ),
        migrations.AlterField(
            model_name='mmiiestudio',
            name='art_infrapatelares_derecha',
            field=models.TextField(blank=True, db_column='artInfrapatelaresDerecha', null=True, validators=[django.core.validators.MaxLengthValidator(512)]),
        ),
        migrations.AlterField(
            model_name='mmiiestudio',
            name='art_infrapatelares_izquierda',
            field=models.TextField(blank=True, db_column='artInfrapatelaresIzquierda', null=True, validators=[django.core.validators.MaxLengthValidator(512)]),
        ),
        migrations.AlterField(
            model_name='mmiiestudio',
            name='art_poplitea_derecha',
            field=models.TextField(blank=True, db_column='artPopliteaDerecha', null=True, validators=[django.core.validators.MaxLengthValidator(512)]),
        ),
        migrations.AlterField(
            model_name='mmiiestudio',
            name='art_poplitea_izquierda',
            field=models.TextField(blank=True, db_column='artPopliteaIzquierda', null=True, validators=[django.core.validators.MaxLengthValidator(512)]),
        ),
        migrations.AlterField(
            model_name='mmiiestudio',
            name='conclusion',
            field=models.TextField(blank=True, db_column='conclusion', null=True, validators=[django.core.validators.MaxLengthValidator(8000)]),
        ),
    ]
