# Generated by Django 5.1.1 on 2026-02-05 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0003_rename_idpaciente_idx_historia_paciente_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarotidasEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_derecha', models.CharField(blank=True, max_length=20, null=True)),
                ('int_derecha', models.CharField(blank=True, max_length=20, null=True)),
                ('ext_derecha', models.CharField(blank=True, max_length=20, null=True)),
                ('com_izquierda', models.CharField(blank=True, max_length=20, null=True)),
                ('int_izquierda', models.CharField(blank=True, max_length=20, null=True)),
                ('ext_izquierda', models.CharField(blank=True, max_length=20, null=True)),
                ('art_vertebrales', models.CharField(blank=True, max_length=20, null=True)),
                ('sugerencias', models.CharField(blank=True, max_length=20, null=True)),
                ('id_com_der', models.PositiveIntegerField(default=0)),
                ('id_com_izq', models.PositiveIntegerField(default=0)),
                ('esp_int_med_der', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('esp_int_med_izq', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('historia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carotidas_estudios', to='main.historiaclinica')),
            ],
            options={
                'verbose_name': 'Estudio de carótidas',
                'verbose_name_plural': 'Estudios de carótidas',
                'db_table': 'carotidas',
                'indexes': [models.Index(fields=['historia'], name='carotidas_historia_idx'), models.Index(fields=['id_com_der', 'id_com_izq'], name='carotidas_com_idx')],
            },
        ),
    ]
