# Generated by Django 5.1.1 on 2026-02-05 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carotidas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carotidasestudio',
            name='art_vertebrales',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='carotidasestudio',
            name='com_derecha',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='carotidasestudio',
            name='com_izquierda',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='carotidasestudio',
            name='ext_derecha',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='carotidasestudio',
            name='ext_izquierda',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='carotidasestudio',
            name='int_derecha',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='carotidasestudio',
            name='int_izquierda',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='carotidasestudio',
            name='sugerencias',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
