# Generated by Django 5.1.1 on 2026-02-27 13:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carotidas', '0002_alter_carotidasestudio_art_vertebrales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carotidasestudio',
            name='fecha_estudio',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
