# Generated by Django 5.1.1 on 2026-03-07 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carotidas', '0003_carotidasestudio_fecha_estudio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carotidasestudio',
            name='com_derecha',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='carotidasestudio',
            name='com_izquierda',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='carotidasestudio',
            name='ext_derecha',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='carotidasestudio',
            name='ext_izquierda',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='carotidasestudio',
            name='int_derecha',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='carotidasestudio',
            name='int_izquierda',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
